name: build_test
on: [push]

jobs:
  build:
    runs-on: arch
    steps:
      - name: fix package cache
        run: rm -fr /var/cache/pacman/pkg/* && pacman -Syy archlinux-keyring --needed --noconfirm && pacman-key --init && pacman-key --populate archlinux
      - name: get dependencies
        run: pacman -Sy nodejs make nasm binutils --needed --noconfirm

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build
        run: make -j$(nproc)
